name: Push To Master Deploy
on:
  push:
    branches:
      - master
    tags:
      - 'drivers/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.8

      - name: Lint
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: cd drivers && make info lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: cd drivers && make info test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        run: |
          export DOCKER_USERNAME=$GITHUB_ACTOR
          cd drivers && make info release
